### ISSUE TITLE
DEV-Post shipment pack slip print

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#10]
hi
Post shipment changes is done (packing list)(1819100151)

pending with jignesh confirmation

thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
hi,
Post shipment screen unknown error in screen 11-1-2019
Navigation 
Expoerts>postshipment>post shipment>EDK pack list system throw error in "unknown is error"

Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi karthi,

kindly assign the report for commercial  pack slip
Navigation
Expoerts>postshipment>post shipment>EDK pack list 
while click print system throw error in "unknown is error"

Thanks 
parthiban.R

**Comment by parthiban25** [comment]
hi karthi,
kindly assign the report for commercial pack slip
Navigation
Expoerts>postshipment>post shipment>EDK pack list
while click print system throw error in "unknown is error"

**Comment by parthiban25** [comment]
hi ,

Srinivasan

Post shipment pack slip 
After testing update PFS

[poshipment packing list in packslip.zip](https://github.com/astpl1998/Subhasri/files/2995213/poshipment.packing.list.in.packslip.zip)

Regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,
packslip print
1. quantity column is remove
2.Remarks column is remove

pre-carriage   by | Export>postshipment>postshipment>.sb/GR   Reconciliation Tab " hyperlink attach notes " Document level "<pre-carriage by>"   field
-- | --
place of   receipt by | Export>postshipment>postshipment>.sb/GR   Reconciliation Tab "address 4 As per contract   L/c" field
vessel /flight   no | Export>postshipment>postshipment>.sb/GR   Reconciliation Tab hyperlink attach notes " Document level "<vessel /flight no>"field
port of   loading | Export>postshipment>postshipment>.sb/GR   Reconciliation Tab  hyperlink attach   notes " Document level "<port of   loading>"field
port of   Discharge | Export>postshipment>postshipment>.sb/GR   Reconciliation Tab " hyperlink attach notes " Document level "<port of Discharge>"field
final   destination | Export>postshipment>postshipment>.sb/GR   Reconciliation Tab hyperlink attach notes " Document level "<final destination>"field

![image](https://user-images.githubusercontent.com/37869674/54866266-9fecaf80-4d97-11e9-81a9-a0606c239cd2.png)

**Comment by Jeyapriyat** [comment]
@srinivasanbaskaran 

report changes completed in live server,kindly check and revert.

**Comment by parthiban25** [comment]
hi,
After Delivery from the customer .check and revert the Report
1.subhasri pigments PVT.LTD -->It is come from EDIT company Details
2.india-->As come from country it as required as Capital
3.Denmark-->it will come three times
 france --> it will come three times
4.SPPL45-45 days-->issue has been resolved
5.precarriage by-->Data Fetching from Export >preshipment>preshipment>SB/GRReconciliation Down link from attach notes Document level enter in Test.report dispaly as Test
6.vessel /flight no -->Data Fetching from Export >preshipment>preshipment>SB/GRReconciliation Down link from attach notes Document level enter in <vessel /flight no>Test.report dispaly as Test
7.should as per customer Requirement-->alerate solution as given
**8.Total value it will come  two times** 
9.H.s.code no--remove the Field
10.contract no-->remove the field

![image](https://user-images.githubusercontent.com/37869674/55378310-188d0200-5536-11e9-9cfc-b4e5beb8f70d.png)

![image](https://user-images.githubusercontent.com/37869674/55378316-1dea4c80-5536-11e9-8cb4-cb789c3f6ff8.png)

**Comment by parthiban25** [comment]
hi 

issue has been resolved(1819100235)


![image](https://user-images.githubusercontent.com/37869674/56111205-ca83ef80-5f74-11e9-919d-0fc5afb34c05.png)
