### ISSUE TITLE
DEV-Preshipment  packing list in packslip 

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#11]
hi,

"preshipment  packing list in packslip (Navigation sales & shipping>packslip >view packslip)(check with jignesh)
"
requirement pending

Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,
Already changes also Done pending with Jignesh

Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,
latest pfs Update



thanks & Regards
Parthiban.R

**Comment by DeviAmitysoft** [comment]
Hi Parthiban,
           I have Raised ticket to get ER file .Ticket id : MAG-71004

**Comment by DeviAmitysoft** [comment]
Hi,
  I have raised ticket to deploy ER file in simulation server.Ticket Id : MAG-71015

**Comment by DeviAmitysoft** [comment]
Hi,
  Report completed on simulation server.Please Check and revert.

**Comment by parthiban25** [comment]
hi,

Packslip print issues has been resolved SP move to Live server

thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi ,
Item qty & value -->3 field as empty 
pls refer the transaction SP/EX/PS/18-19/271.
screen shot is reference 
[packslip.zip](https://github.com/astpl1998/Subhasri/files/2864333/packslip.zip)


thanks & regards
parthiban.R

**Comment by DeviAmitysoft** [comment]
Hi,
  I have corrected above mentioned issue.Kindly check and revert

**Comment by parthiban25** [comment]
hi,
Testing issue .Kindly correct the report
pls correct the Total & Next continous pages & Authorized signatory second page bottom
![image](https://user-images.githubusercontent.com/37869674/52934207-bc9e5d80-337b-11e9-8e55-a36c63a37142.png)
![image](https://user-images.githubusercontent.com/37869674/52934322-1e5ec780-337c-11e9-838c-850190384311.png)

**Comment by parthiban25** [comment]
hi Devi ,
packslip
1. pages bottom Signature authorized is Disappear  refer screen shot
2.Declaration is missing
3.item code is missing

![image](https://user-images.githubusercontent.com/37869674/53468544-adf12e00-3a80-11e9-8cb6-4d73bcdc8847.png)

**Comment by parthiban25** [comment]
testing issues as on 1-3-2018

1.kindly check 
Signature(space required between subhasri pigment & Authorized signature)
subhasri pigments pvt.ltd


authorized signature

2.Data not fetched  in the circle column mentioned in screen shot

![image](https://user-images.githubusercontent.com/37869674/53634083-3ae1e600-3c3f-11e9-9bec-467d98165be2.png)

**Comment by DeviAmitysoft** [comment]
Hi,
  There is no data for above mentioned invoice number.Kindly check and revert.

**Comment by parthiban25** [comment]
Latest PFS
[preshipment packing list in packslip.zip](https://github.com/astpl1998/Subhasri/files/2955294/preshipment.packing.list.in.packslip.zip)

**Comment by srinivasanbaskaran** [comment]
@Jeyapriya ... Please do the needful...

**Comment by parthiban25** [comment]
hi
latest PFS

[preshipment packing list in packslip.zip](https://github.com/astpl1998/Subhasri/files/2995327/preshipment.packing.list.in.packslip.zip)


regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,

6a | pre-carriage by | Export>postshipment>postshipment>.sb/GR   Reconciliation Tab " hyperlink attach notes " Document level "<pre-carriage by>"   field
-- | -- | --
6b | place of receipt by | Export>postshipment>postshipment>.sb/GR   Reconciliation Tab "address 4 As per contract   L/c" field
6c | vessel /flight no | Export>postshipment>postshipment>.sb/GR   Reconciliation Tab hyperlink attach notes " Document level "<vessel /flight no>"field
6d | port of loading | Export>postshipment>postshipment>.sb/GR   Reconciliation Tab  hyperlink attach   notes " Document level "<port of   loading>"field
6e | port of Discharge | Export>postshipment>postshipment>.sb/GR   Reconciliation Tab " hyperlink attach notes " Document level "<port of Discharge>"field
6f | final destination | Export>postshipment>postshipment>.sb/GR   Reconciliation Tab hyperlink attach notes " Document level "<final destination>"field

Quantity | remove the   field
-- | --

Remarks | remove the   field
-- | --
![image](https://user-images.githubusercontent.com/37869674/54866312-2d300400-4d98-11e9-8f04-27394ff33899.png)

**Comment by parthiban25** [comment]
hi,
latest PFS

[preshipment packing list in packslip.zip](https://github.com/astpl1998/Subhasri/files/3006776/preshipment.packing.list.in.packslip.zip)

**Comment by Jeyapriyat** [comment]
@srinivasanbaskaran 

changes completed in simulation server ,kindly check and revert

**Comment by parthiban25** [comment]
hi,

report launched throw an error
![image](https://user-images.githubusercontent.com/37869674/55152023-8374bc80-5175-11e9-9f62-95e57d94cf39.png)

**Comment by Jeyapriyat** [comment]
@parthiban25 

report lanuched ,kindly check it

**Comment by parthiban25** [comment]
hi ,
pls refer screen shot
Two print is required
From Two Different Address(purpose one as Insurance another one as customer)
issues use the transaction no :SP/EX/PS/18-199/31
1.first print is same address it ok
2.second print as different address
take export refer Doc no:sales & shipping >packslip>view packsip SP/EX/PS/18-199/31  refer Doc no SOC/EXP/18-19/300
1 (a)consignee no:
First line Data:Goto sale order "customer code" then CUstomer" Identification no" field
second line as:Goto sale order "customer code" against address "country Descrption" field
1(b)Buyer (if other than consignee)
First line Data:Goto sale order "ship to customer " then CUstomer" Identification no" field
second line as:Goto sale order "ship to customer" against address "country Descrption" field

![image](https://user-images.githubusercontent.com/37869674/55381454-d61cf280-5540-11e9-8801-561020ca2144.png)
![image](https://user-images.githubusercontent.com/37869674/55381457-da491000-5540-11e9-8c8b-93f1425c99ad.png)

**Comment by parthiban25** [comment]
hi,
SP/EX/PS/18-19/300,SP/EX/PS/18-19/319
packslip error .while click the print system throw an error"

Invalid length parameter passed to the LEFT or SUBSTRING function. Invalid length parameter passed to the LEFT or SUBSTRING function.".kindly do it earliest

![image](https://user-images.githubusercontent.com/37869674/56110869-a247c100-5f73-11e9-8db0-d298195cde76.png)

--

**Comment by parthiban25** [comment]
issue has been resolved
as on 22-4-2019
Hi jignesh 

Kindly check the preshipment  packslip  issue resolved
Changes are Done for attached notes Enter in Document level Tab
<Pre-Carriage by>ANK
<Place of Receipt by>Ankleshwar
<Vessel/Flight No>maesk
<Port of Loading>ANK
<Port of Discharge>USA
<Final Destination>USA
![image](https://user-images.githubusercontent.com/37869674/56498270-93867e80-651e-11e9-84ae-f3bb370d2233.png)

**Comment by parthiban25** [comment]
![image](https://user-images.githubusercontent.com/37869674/56498590-03493900-6520-11e9-883d-ca8a738673f5.png)
