### ISSUE TITLE
ISS-Preshipment packslip

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#111]
latest update issue as on 21-5-2019
navigation 
sales & shipping-->packslip-->view packslip sp/ex/ps/19-20/015
1.Add   one print (customs)Address Changes must .remaining Data are Refer Existing   Report     
2.correction Every page Header & footer    is Required.page number Required     
3.total Value as line required    
 4.case 1:one line item multiple Grade & pallets it will come next to   next line come refer screen shot     
5.case 2:Two line item Different Grade & pallets it will come Correct   Line  Required
--

[1.Prepacking list.zip](https://github.com/astpl1998/Subhasri/files/3201758/1.Prepacking.list.zip)

![image](https://user-images.githubusercontent.com/37869674/58091800-2d0d8280-7be8-11e9-8705-0dde4ec44124.png)

![image](https://user-images.githubusercontent.com/37869674/58091919-7958c280-7be8-11e9-8ff2-a17039f5e12b.png)
![image](https://user-images.githubusercontent.com/37869674/58091923-7bbb1c80-7be8-11e9-9f4c-56c4b8a5f387.png)

**Comment by parthiban25** [comment]
pre shipment above mentioned all correction & additional requirement also completed as on 3-7-2019

Two Print as Completed pls note it as following procedure
1.preshipment packslip(insurance )refer Screen shot 1 &3 put as input transaction no:sp/ex/ps/19-20/045
2.preshipment packslip(customes)refer screen shot 2&4 put as input transaction no:sp/ex/ps/19-20/045-C   for every packslip for customs  using (-C)

![image](https://user-images.githubusercontent.com/37869674/60565714-49254780-9d82-11e9-9b54-989a96631f07.png)
![image](https://user-images.githubusercontent.com/37869674/60565717-4b87a180-9d82-11e9-9d00-a6afc9b99b7e.png)
![image](https://user-images.githubusercontent.com/37869674/60565731-52161900-9d82-11e9-8b46-242d111416ea.png)
![image](https://user-images.githubusercontent.com/37869674/60565735-56423680-9d82-11e9-973d-11a98dcdb218.png)

**Comment by parthiban25** [comment]
hi arunchalam

kindly update the latest Deliverables in pre shipment packslip
1.New Development
2.correction
update in Githup

**Comment by Arunachalamamitysoft** [comment]
[pre_pack_slip.zip](https://github.com/astpl1998/Subhasri/files/3381323/pre_pack_slip.zip)

**Comment by parthiban25** [comment]
hi,
SP is ok,
Latest Design update

**Comment by raju-kurup** [comment]
Latest sp and design submitted to Ramco
