### ISSUE TITLE
ISS-Post shipment packslip

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#112]
Latest update as on 21-5-2019
Exports-->postshipment--->postshipment

1.Repeated   the Data is wrong only Enter in Last Data of invoice  
2.More space is required B/w Data and total Amount    
3.print format size is Decrease because of stapler is print Data is   hidden    
 4.Every page Header & footer  is   Required.page number Required     
5.case 1:one line item multiple Grade & pallets it will come next to   next line come refer screen shot    
 6.case 2:Two line item Different Grade & pallets it will come Correct   Line  Required

![image](https://user-images.githubusercontent.com/37869674/58084692-fd0ab300-7bd8-11e9-93fa-2388f10cb73f.png)
![image](https://user-images.githubusercontent.com/37869674/58084700-0136d080-7bd9-11e9-85e3-29f6feb4e661.png)
![image](https://user-images.githubusercontent.com/37869674/58084721-05fb8480-7bd9-11e9-85c8-c358fce94796.png)
![image](https://user-images.githubusercontent.com/37869674/58084734-0b58cf00-7bd9-11e9-8436-6fa1fc8e9f36.png)

--

**Comment by stephendharmaraj** [comment]
hi parthiban,

please check subasri live server and revert it back

thanks,
Balan A Stephen J

**Comment by parthiban25** [comment]
hi Stephen,
1.refer the transaction
1920100012
2.refer screen shot one (vertical line as remove)
3.refer screen shot two (two lines as merge i want required as single line )
4.refer screen shot three(page number come from top required )(continous page 1/2 like that)
5.refer screen shot  threemarks,no.of kinds,Descrption of goods,Pkgs,Grade ,Lot,Netwt.all required
6.refer screeen shot four (remove the field in second page only )

![image](https://user-images.githubusercontent.com/37869674/58453962-93d7f200-813a-11e9-815a-2b75afba194c.png)
![image](https://user-images.githubusercontent.com/37869674/58453986-a81bef00-813a-11e9-82ac-d4d18ebb4bb5.png)
![image](https://user-images.githubusercontent.com/37869674/58453992-afdb9380-813a-11e9-9801-837465aec38a.png)
![image](https://user-images.githubusercontent.com/37869674/58453995-b66a0b00-813a-11e9-9849-352ff03fcd55.png)

**Comment by stephendharmaraj** [comment]
hi parthiban,
please check now and revert it back.

thanks,
Balan A Stephen J

**Comment by parthiban25** [comment]
hi stephen.J
1920100012
pls check testing issues again 29-5-2019
1.Refer screen shot one left corner right corner not required
2.Refer screen shot one Pre-"carrier" is missing:
3.Refer screen shot two vertical line as removed can you check once again 
4.Refer screen shot three left corner right corner not required
5.Refer screen shot three Total value is required two line required
![image](https://user-images.githubusercontent.com/37869674/58547417-eee61380-8224-11e9-9a09-56e382dffe1a.png)
![image](https://user-images.githubusercontent.com/37869674/58547423-f1486d80-8224-11e9-978d-163bf4650e8a.png)
![image](https://user-images.githubusercontent.com/37869674/58547435-f73e4e80-8224-11e9-86a1-854b999b8e62.png)

**Comment by stephendharmaraj** [comment]
hi parthiban,
please check now and revert it back.

thanks,
Balan A Stephen J

**Comment by stephendharmaraj** [comment]
hi parthiban,
please check now and revert it back.

thanks,
Balan A Stephen J
[RAMCOUSER_subhasripigments_451021_79dd613e-d8e6-4049-8ebf-40cbfcf3bf5f.pdf](https://github.com/astpl1998/Subhasri/files/3236357/RAMCOUSER_subhasripigments_451021_79dd613e-d8e6-4049-8ebf-40cbfcf3bf5f.pdf)

**Comment by parthiban25** [comment]
issue has been Resolved

**Comment by parthiban25** [comment]
hi Badam,

kindly update the latest Deliverables in post shipment packslip
1.New Development
2.correction
update in Githup

**Comment by parthiban25** [comment]
hi,

kindly update the Latest Sp and Design

**Comment by raju-kurup** [comment]
latest sp and design taken and submitted to Ramco
