### ISSUE TITLE
ISS-Post shipment invoice

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#113]
latest update as on 21-5-2019
Export-->postshipment--->postshipment
1.SPPL45D-->Remove the Data
2.Qty,Rate Amount   Line Required Refer screen shot
3.Repeated the Data is wrong only Enter in Last Data of invoice
4.More space is required B/w Data and total Amount
5.print format size is Decrease because of stapler is print Data is hidden
6.Every page Header & footer  is Required.page number Required
7.case 1:one line item multiple Grade & pallets it will come next to next line come refer screen shot
8.case 2:Two line item Different Grade & pallets it will come Correct Line  Required
![image](https://user-images.githubusercontent.com/37869674/58085128-c2554a80-7bd9-11e9-86b5-9eeaa68e7f8a.png)
![image](https://user-images.githubusercontent.com/37869674/58085133-c6816800-7bd9-11e9-840a-9d9bbc2c7e09.png)
![image](https://user-images.githubusercontent.com/37869674/58085145-cbdeb280-7bd9-11e9-88e6-19c925ede807.png)
![image](https://user-images.githubusercontent.com/37869674/58085189-e6b12700-7bd9-11e9-9afb-bb69a603133b.png)

**Comment by stephendharmaraj** [comment]
hi parthiban,
please check and revert it back.
thanks,
Balan A Stephen J

**Comment by parthiban25** [comment]
hi stephen,

Pls find the Testing issues against postshipment invoice
1.In refer screen shot one  invoice print Top Extra two lines cames can you  remove this line
2.refer screen shot two lines are not connected can you connected the two lines
3.refer screen shot three red lines as remove & yellow lines added the Header field i.e..marks, no.of kinds,Descrption of goods,quantity,rate ,amount



![image](https://user-images.githubusercontent.com/37869674/58703508-8f276e00-83c6-11e9-8889-69c031580f85.png)
![image](https://user-images.githubusercontent.com/37869674/58703518-9189c800-83c6-11e9-9726-cd49920fbc54.png)
![image](https://user-images.githubusercontent.com/37869674/58703521-951d4f00-83c6-11e9-98d5-1a0052c72966.png)

**Comment by stephendharmaraj** [comment]
hi parthiban,
please check and revert it back.
thanks,
Balan A Stephen J

**Comment by parthiban25** [comment]
hi stephan,
pls find the attached
![image](https://user-images.githubusercontent.com/37869674/58708509-a28e0580-83d5-11e9-9176-977238536cff.png)

**Comment by stephendharmaraj** [comment]
hi parthiban,
please check and revert it back.
thanks,
Balan A Stephen J

**Comment by parthiban25** [comment]
hi, 

kindly check the print Refer screen shot line is missing
![image](https://user-images.githubusercontent.com/37869674/58744775-b3d22300-8464-11e9-9734-7408c1b536ac.png)

**Comment by parthiban25** [comment]
hi 
Report correction are Done Thank you so much for my requriment you corrected Perfectly

sample print
![image](https://user-images.githubusercontent.com/37869674/58744824-a701ff00-8465-11e9-910a-9b74af0a1deb.png)
![image](https://user-images.githubusercontent.com/37869674/58744826-ab2e1c80-8465-11e9-84da-f8b18fed9b89.png)

**Comment by parthiban25** [comment]
hi,
pls find the Correction for Payterm in commerical invoice
It is come in print Begium as Country remove the Field and add the same  payterm Descrption "45 Days from B/L Date"any Doubt Refer the Screen shot
![image](https://user-images.githubusercontent.com/37869674/58779669-46ed9300-85f4-11e9-81da-da8fdc8a4331.png)
![image](https://user-images.githubusercontent.com/37869674/58779672-494fed00-85f4-11e9-80a9-f697e838374d.png)

**Comment by parthiban25** [comment]
issue has been resolved as on  1-6-2019
