### ISSUE TITLE
ISS-Sales Register for GST(D-cube) correction

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#114]
added   10 fields (mail 4/5/2019)     
1.customer shared order line wise field    
2.Required Extra field Next change from regular field    
3.shipping Bill No:4216185    
4.shipping bill Date:16-05-2019    
5.port code:1NAKV6     192010034
--

[65.Sales Register for GST recerived 4-5-2019.zip](https://github.com/astpl1998/Subhasri/files/3215318/65.Sales.Register.for.GST.recerived.4-5-2019.zip)

**Comment by parthiban25** [comment]
sales Register Correction is started as on 21-6-2019

**Comment by karthikeyanamitysoft** [comment]
[2sales_register_pop.zip](https://github.com/astpl1998/Subhasri/files/3330225/2sales_register_pop.zip)

**Comment by parthiban25** [comment]
Above mentioned Correction are Done as on 27-6-2019
1.Sales order against Data Not Fetching in D-cube Report 
2.Shipping bill number field coming as Blank
3.shipping bill Date field coming as undefined
sample in Data
COBI-1920100006
sale order--soc/exp/18-19/319
packslip--sp/ex/ps/19-20/007
preshipment--sp/ex/in/19-20/007
cif value(FC)48024.00
freight(FC)140
insurance amount 19.21
Exchange rate 67.7500
FOB value(FC)47883.71
FOB Value3244122.03
shipping bill number:test0002
shipping  bill Date:24/4//2019
port code:USA


kindly refer the Excel file 

[sales Register D-cube.zip](https://github.com/astpl1998/Subhasri/files/3333640/sales.Register.D-cube.zip)

**Comment by parthiban25** [comment]
sales register correction has been Done 

[sales Register D-cube report .zip](https://github.com/astpl1998/Subhasri/files/3334402/sales.Register.D-cube.report.zip)

**Comment by parthiban25** [comment]
kindly update the Latest SP

**Comment by parthiban25** [comment]
Latest Sp update in D-cube as on 19-7-2019
sales Register for GST D-cube

[GST SALES REGISTER REPORT.zip](https://github.com/astpl1998/Subhasri/files/3410007/GST.SALES.REGISTER.REPORT.zip)
