### ISSUE TITLE
ISS-Purchase GST Register(D-cube)correction

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#115]
correction 
Add 3   Fields in D-cube report(4/5/2019)    
 1.RCM taxable field     if tax class as GTA -->RCM populated     if tax class other-->Taxable      2.state code field -->Tax registration code start number (2   Digits)     3.without tax also include in report
--
[67.GST Purchase Register as on 13-5-2019.zip](https://github.com/astpl1998/Subhasri/files/3216873/67.GST.Purchase.Register.as.on.13-5-2019.zip)

**Comment by stephendharmaraj** [comment]
hi parthiban,
i have completed . please check and revert it back
Thanks,
[Purchase_Register_rpt_pop_.zip](https://github.com/astpl1998/Subhasri/files/3330231/Purchase_Register_rpt_pop_.zip)

Balan A Stephen J
[Purchase_Register_rpt_pop_.zip](https://github.com/astpl1998/Subhasri/files/3330229/Purchase_Register_rpt_pop_.zip)

**Comment by parthiban25** [comment]
hi stephen,

pls check the Excel file

kindly added the header field in excel file 

[purchase register.zip](https://github.com/astpl1998/Subhasri/files/3333735/purchase.register.zip)

**Comment by parthiban25** [comment]
Testing and update 
1.UGST % &UGST Value ---->loggic can be Removed.We required blank
2.control fields alignment as sequence of order refer in Excel in correction

[Purchase Register 1.xlsx](https://github.com/astpl1998/Subhasri/files/3341449/Purchase.Register.1.xlsx)

**Comment by parthiban25** [comment]
correction ha been Done

**Comment by parthiban25** [comment]
Kindly update the Latest SP

**Comment by parthiban25** [comment]
latest sp update (D-cube)as on 19-7-2019
purchase GST Register
[RAMCO PURCHASE REGISTER.zip](https://github.com/astpl1998/Subhasri/files/3409977/RAMCO.PURCHASE.REGISTER.zip)
