### ISSUE TITLE
ISS-Issue list (D-cube Report) correction

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#117]
add 2   fields(30/4/2019)     
filter :    
 1.Date From:     
2.Date To:   
  (data from Issue Date in report    launching)
--

**Comment by parthiban25** [comment]
issue has been resolved 
move to Live server as on 27-5-2019

[D-cube Issue01.xlsx](https://github.com/astpl1998/Subhasri/files/3223537/D-cube.Issue01.xlsx)

**Comment by karthikeyanamitysoft** [comment]
[Issue_List_Report_Pop.zip](https://github.com/astpl1998/Subhasri/files/3223550/Issue_List_Report_Pop.zip)

**Comment by karthikeyanamitysoft** [comment]
magna ticket id : MAG-80892

**Comment by parthiban25** [comment]
I have tested in Live server error shown as on 29-5-2019
while click the Executed view system throw an error
refer screen shot
![image](https://user-images.githubusercontent.com/37869674/58525818-b88ba280-81ea-11e9-9b60-7c99d881b3ab.png)

**Comment by parthiban25** [comment]
correction has been Done

**Comment by parthiban25** [comment]
Kindly update the Latest SP

**Comment by parthiban25** [comment]
Latest Sp Update(D-cube) as on 19-7-2019
issue list Report
[ISSUE LIST REPORT.zip](https://github.com/astpl1998/Subhasri/files/3409966/ISSUE.LIST.REPORT.zip)
