### ISSUE TITLE
DEV-Preshipment or proforma invoice

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#12]
hi,

preshipment or proforma invoice(check with jignesh)

Requirement pending

Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,

Post shipment proforma invoice clarification is Done and  make PFS also Done

Thanks & regards
Parthiban.R

**Comment by karthikeyanamitysoft** [comment]
Dear Devi,

Kindly do the changes.

Regards,
Karthi

**Comment by parthiban25** [comment]
hi,
latest PFS
[preshipment or proforma invoice.zip](https://github.com/astpl1998/Subhasri/files/2854243/preshipment.or.proforma.invoice.zip)

thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
hi Devi 
latest PFS update in Yellow lines
[preshipment or proforma invoice.zip](https://github.com/astpl1998/Subhasri/files/2865038/preshipment.or.proforma.invoice.zip)


Thanks & Regards
Parthiban.R

**Comment by DeviAmitysoft** [comment]
Hi Parthiban,
                 I have completed the Report,Kindly check and revert.

**Comment by parthiban25** [comment]
hi,

I have check the Transaction is empty Data came 
pls check

**Comment by DeviAmitysoft** [comment]
Hi,
  For What input  empty data comming..

**Comment by parthiban25** [comment]
hi,

Testing issues

1.Total value is corrected
2.Continous Pages pages Header & footer is missing in Page 2:
3.Other Details Not fetched  in report refer in screen shot PFS
4.column as remove in print

![image](https://user-images.githubusercontent.com/37869674/52995995-34cf5680-3442-11e9-8f05-92ea5274db2f.png)

**Comment by DeviAmitysoft** [comment]
Hi,
  Completed Above mentioned corrections.Kindly check and revert.

**Comment by parthiban25** [comment]
I have tested some New issues came in report
1.continous pages in 2 screen missing
2.Total value is wrong
3.Note harcoded in the field Navigation Exports>preshipment>preshipment>SP/EX/PS/18-19/106.contract LC details Tab against Attach notes.Lines level notes  refer Screen shot
4.Authorized signature page centre came
![image](https://user-images.githubusercontent.com/37869674/53335673-15dd3280-3922-11e9-8006-a8b78c018724.png)

![image](https://user-images.githubusercontent.com/37869674/53335685-1e356d80-3922-11e9-885e-a4b7e9b2eb13.png)
![image](https://user-images.githubusercontent.com/37869674/53335691-24c3e500-3922-11e9-88b6-2a74f4621cec.png)

**Comment by parthiban25** [comment]
hi,

issue has been resolved 
SP Moving to LIve server

thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
kindly conformed SP move to live sever

**Comment by parthiban25** [comment]
latest PFS
[preshipment or proforma invoice.zip](https://github.com/astpl1998/Subhasri/files/2955291/preshipment.or.proforma.invoice.zip)

**Comment by parthiban25** [comment]
Testing issue for Proforma invoice
refer the latest PFS issues is marked 
[preshipment or proforma invoice.zip](https://github.com/astpl1998/Subhasri/files/2964970/preshipment.or.proforma.invoice.zip)


Regards
parthiban.R

**Comment by srinivasanbaskaran** [comment]
Please do the needful ....

**Comment by Jeyapriyat** [comment]
@srinivasanbaskaran 
changes,completed,kindly check and revert

**Comment by parthiban25** [comment]
hi,

check the Latest PFS

[preshipment or proforma invoice.zip](https://github.com/astpl1998/Subhasri/files/2995330/preshipment.or.proforma.invoice.zip)


regards
Parthiban.R

**Comment by Jeyapriyat** [comment]
@srinivasanbaskaran 
changes completed in simulation server,kindly check and revert.
i have attached reference report file.
[RAMCOUSER_subhasripigments_45711003_cb7bff17-8916-4b16-aacc-f5cc6a6bcd82.pdf](https://github.com/astpl1998/Subhasri/files/3012035/RAMCOUSER_subhasripigments_45711003_cb7bff17-8916-4b16-aacc-f5cc6a6bcd82.pdf)

**Comment by parthiban25** [comment]
hi ,
pls refer screen shot
**Two print is required** 
**From Two Different Address(purpose one as  Insurance another one as customer)**
issues use the transaction no :SP/EX/IN/18-19/319
1.first print is same address it ok 
2.second print as different address
take export refer no:SOC/EXP/18-19/300  
1 (a)consignee no:
First line Data:Goto sale order "customer code" then CUstomer" Identification no" field
second line as:Goto sale order "customer code" against address "country Descrption" field
1(b)Buyer (if other than consignee)
First line Data:Goto sale order "ship to customer " then CUstomer" Identification no" field
second line as:Goto sale order "ship to customer" against address "country Descrption" field

3.precarriage by:Exports>preshipment>preshipment:SP/EX/PS/18-19/106 contract L/C Details Tab hyperlink attach notes Document level notes<precarriage by>test as Display in report
4.vessel /flight no:Exports>preshipment>preshipment:SP/EX/PS/18-19/106 contract L/C Details Tab hyperlink attach notes Document level notes<vessel /flight no:>test as Display in report

5. Attach notes : "line level Document entity "-->remove the loggic
6.first attach note :Document level entry from print in Down amount in words next line left down what ever enter line format it will come refer screen shot in red box  
7.second attach notes:document level entry from print Descrption of Good last it will come what ever enter line format it will come refer screen shot in violet box

8.IE Code no:remove the Field
9.shippingbill no& date:remove the Field
10.bill of loading no & date:remove the Field
11.PAN no :remove the Field
12.GST no:remove the Field
![image](https://user-images.githubusercontent.com/37869674/55381081-c2bd5780-553f-11e9-8a9e-7701ffce338b.png)
![image](https://user-images.githubusercontent.com/37869674/55381090-c6e97500-553f-11e9-9312-8f55acf29e6b.png)
![image](https://user-images.githubusercontent.com/37869674/55381102-cc46bf80-553f-11e9-9f4c-9c82cf004ce5.png)

**Comment by parthiban25** [comment]
hi sir,

while click the print Report launched like this error came.pls refer screen shot (13-4-2019)

![image](https://user-images.githubusercontent.com/37869674/56075446-8bbd3080-5de0-11e9-8443-67d6db0981d4.png)

**Comment by parthiban25** [comment]
issue has been resolved as on 22-4-2019
Attach note Details Enter like this format transaction no: SP/EX/IN/18-19/319
<pre carriage by >road
<vessel/flight no>mask
<DRAWBACK TARIFF CODE>320499 (B)
<HS CODE NO> 
<EXPORT SCHEME>SHIPMENT UNDER DUTY DRAWBACK SCHEME

<Tax Detail>DRAWBACK TARIFF CODE : 320499 (B)
HS CODE NO.: 32041761
EXPORT SCHEME : SHIPMENT UNDER DUTY 
DRAWBACK SCHEME
PAN No.: AABCS1337G
IEC Code No.: 0395064252 
GST No.: 24AABCS1337G1ZR
Shipping Bill No. & Date.: 
Bill of Lading No. & Date.:
<4> We intend to claim rewards under Merchandise Exports from India Scheme (MEIS).
<5> Exports made under EPCG scheme, against EPCG license no. 0330048767 Dt. 22.02.2018 & 0330049431 Dt.19.06.2018.

<net>total  Net Weight :1,kgs
<Gross>total Gross weight :11kgs
<pallet>Total pallets:02 pallets

<Freight>fright:USD9.00
<Ins>insurance USD 2.200
<FO>FOB:usd ,549280
<1>The goods are covered under post shipment DBK scheme SR.no3204998
<2>we shall claim Drawback after availement input tax facility under ITC rules 2017

<3>Export scheme:shipment under Drawback scheme


<net>total  Net Weight :1,kgs
<Gross>total Gross weight :11kgs
<Pallet>Total pallets:02 pallets

<Freight>fright:USD9.00
insurance USD 2.200
FOB:usd ,549280
The goods are covered under post shipment DBK scheme SR.no3204998
we shall claim Drawback after availement input tax facility under ITC rules 2017

Export scheme:shipment under Drawback scheme
![image](https://user-images.githubusercontent.com/37869674/56500162-5ffc2200-6527-11e9-972e-b15c5491c24c.png)

![image](https://user-images.githubusercontent.com/37869674/56500170-65596c80-6527-11e9-894b-cd2bd1b75e2c.png)

![image](https://user-images.githubusercontent.com/37869674/56500177-6a1e2080-6527-11e9-9853-7192ea39b198.png)

**Comment by parthiban25** [comment]
![image](https://user-images.githubusercontent.com/37869674/56500274-b9645100-6527-11e9-920a-60bd70e76b5d.png)
![image](https://user-images.githubusercontent.com/37869674/56500275-bb2e1480-6527-11e9-9a46-d5684fe6b862.png)
![image](https://user-images.githubusercontent.com/37869674/56500281-bd906e80-6527-11e9-8f74-4790b7490893.png)
