### ISSUE TITLE
ISS-Tank Inward Register(D-cube)correction+gate Entry 1 point correction

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#120]
correction 2 fields+ (Gate Entry customization Correction 2 points)
1.As you find out issue in Gate entry that it is not Validating Received qty. based on PO qty. which was early it was validating & how to enter exit time.
2.In D-cube report Exit time is not capturing, earlier report is not coming so i am unable to explain more about report.

**Comment by Arunachalamamitysoft** [comment]
[Maintain gate entry.zip](https://github.com/astpl1998/Subhasri/files/3329650/Maintain.gate.entry.zip)

**Comment by parthiban25** [comment]
Gate Entry  screen one point has been closed as on 26-6-2019
pending D-cube Report in Tank Register

**Comment by parthiban25** [comment]
Two points are corrected
1.Maintain Gate Entry screen validate Receiving /shipping qty added
2.In D-cube report Tanker Register merge the Two fields
[Tanker D-cube report.xlsx](https://github.com/astpl1998/Subhasri/files/3337756/Tanker.D-cube.report.xlsx)

**Comment by parthiban25** [comment]
hi arunchalam,

kindly update the Latest Sp

**Comment by parthiban25** [comment]
hi,
latest Sp update in Github#36
Tank Register D-cube report
