### ISSUE TITLE
ISS-CDI Print issue

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#121]
navigation
Receivable management>CDI>View CDI

In  CDI screen comments Field Data Enter 
i.e..that as populated in customization print "order no : "field
1.Data Fetching from Comments and “order no”print
2.Date is removed
Refer as print
![image](https://user-images.githubusercontent.com/37869674/58092365-86c27c80-7be9-11e9-8fa3-bc7a0b5358f2.png)
![image](https://user-images.githubusercontent.com/37869674/58092370-8924d680-7be9-11e9-98ce-b4417f91116f.png)

**Comment by stephendharmaraj** [comment]
hi parthiban,
please check and revert it back.
thanks,
Balan A Stephen J

**Comment by parthiban25** [comment]
hi,
Checked and send to customer and Revert back
![image](https://user-images.githubusercontent.com/37869674/58745060-1d543080-8469-11e9-91fb-98f5eee50cc2.png)
![image](https://user-images.githubusercontent.com/37869674/58745061-21804e00-8469-11e9-8527-78eef3d1c053.png)

**Comment by parthiban25** [comment]
issue resolved as on 1-6-2019
![image](https://user-images.githubusercontent.com/37869674/58747899-07596680-848f-11e9-8777-8b6660331444.png)
