### ISSUE TITLE
DEV-Postshipment commerical invoice

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#13]
hi,

postshipment commeical invoice(check with jignesh)
 Requirement pending

Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,

Required and changes also pending with jignesh

Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,
Commerical invoice UDS Print 
old UDS navigation Export >postshipment>postshipment>enter the transaction "1819100120" click the postshipment Documentary top of commerical invoice print
New UDS  navigation Export >postshipment>postshipment
Pls Refer the latest PFS

[postshipment or commerical invoice.zip](https://github.com/astpl1998/Subhasri/files/2908930/postshipment.or.commerical.invoice.zip)

Regards
Parthiban>R

**Comment by karthikeyanamitysoft** [comment]
Design completed, waiting for deliverables ticket id : SUPI-238

**Comment by parthiban25** [comment]
pls refer the Latest PFS
[postshipment or commerical invoice.zip](https://github.com/astpl1998/Subhasri/files/2955289/postshipment.or.commerical.invoice.zip)

**Comment by parthiban25** [comment]
Testing issues for commerical invoice
Refer latest PFS for next sheet mentioned the issues as remarks

[postshipment or commerical invoice.zip](https://github.com/astpl1998/Subhasri/files/2964599/postshipment.or.commerical.invoice.zip)

kindly clarification for print & changes in UDS for search screen

**Comment by Jeyapriyat** [comment]
@srinivasanbaskaran 
issue completed,kindly check and revert.
1819100120 this invoice no launched in simulation server.
vessel/flight and notify party this two column value not in base screen

**Comment by srinivasanbaskaran** [comment]
[18191000120.docx](https://github.com/astpl1998/Subhasri/files/2994639/18191000120.docx)
Invoice No: 1819100120 is not launched in Simulation server . Please do the needfiul...

Screenshot attached for your references...

**Comment by Jeyapriyat** [comment]
@srinivasanbaskaran 
report launched,kindly check and revert.
i have attached latest sp.
[new sp.zip](https://github.com/astpl1998/Subhasri/files/2995192/new.sp.zip)

**Comment by parthiban25** [comment]
hi,
srinivasan 
Update PFS 

commerical invoice pls check

[postshipment or commerical invoice.zip](https://github.com/astpl1998/Subhasri/files/2995320/postshipment.or.commerical.invoice.zip)


Regards
parthiban.R

**Comment by Jeyapriyat** [comment]
@srinivasanbaskaran 
changes completed , kindly check and revert.

**Comment by srinivasanbaskaran** [comment]
Hi Parthi Anna,

Please check this report & Revert incase of any details missing... 

Regards,

Srinivasan Baskaran

**Comment by parthiban25** [comment]
hi,
After Delivery from the customer .check and revert the Report
1.subhasri pigments PVT.LTD -->It is come from EDIT company Details
2.india-->As come from country it as required as Capital
3.Denmark& France -->issue has been resolved
4.SPPL45-45 days-->issue has been resolved
5.precarriage by-->Data Fetching from Export >preshipment>preshipment>SB/GRReconciliation Down link from attach notes Document level enter in <precarriage by>Test.report dispaly as Test
6.vessel /flight no -->Data Fetching from Export >preshipment>preshipment>SB/GRReconciliation Down link from attach notes Document level enter in <vessel /flight no>Test.report dispaly as Test
7.should as per customer Requirement-->alerate solution as given
8.there should be edit option to mention the paymentterms as per customer order--->alerate solution given to customer

![image](https://user-images.githubusercontent.com/37869674/55377908-a667ed80-5534-11e9-947e-85a6f89c0708.png)

**Comment by parthiban25** [comment]
hi, 
issue has been resolved

![image](https://user-images.githubusercontent.com/37869674/56109308-96f19700-5f6d-11e9-8580-bb52bd9912b7.png)
![image](https://user-images.githubusercontent.com/37869674/56109323-a40e8600-5f6d-11e9-9c8b-6365b639c687.png)
