### ISSUE TITLE
ISS-Postshipment commerical invoice

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#145]
Testing issue by MKT as on 7-6-2019
navigation Exports--->postshipments-->postshipments-->commerical invoice
1.Payterm is required.
Already Data is coming but Not Required.In means while Data pulling from Exports--->postshipments---->postshipment Transaction no:1920100030.In SB/GR Reconciliation Tab as payterm code against "Descrption "field

refer Screen shot 1

2.Refer screen shot 2 Alignment as centre
3. PAN No:as capital refer screen shot 3
 4.GST NO:ascapital refer screen shot 3

5.Refer screen  shot 4:item code as same LOT no,pallet no,Merge in one 
6.Refer screen shot 5:Data pulling in "pkg from /to "& "Lot no"
Packslip no:sp/ex/ps/19-20/045
sale order no: "spl/exp/19-20/030"
COBI:"1920100044"

![image](https://user-images.githubusercontent.com/37869674/59755135-0739d300-92a5-11e9-8f93-078ec17ff06b.png)
![image](https://user-images.githubusercontent.com/37869674/59755146-0bfe8700-92a5-11e9-9f48-ffb035357495.png)
![image](https://user-images.githubusercontent.com/37869674/59755158-102aa480-92a5-11e9-9c4a-f80f8fa56151.png)
![image](https://user-images.githubusercontent.com/37869674/59755180-16b91c00-92a5-11e9-86f6-1eeeb31ae340.png)
![image](https://user-images.githubusercontent.com/37869674/59755199-1c166680-92a5-11e9-8263-4a81e75fe26f.png)

**Comment by parthiban25** [comment]
commerical invoice correction has been Done as on 28-6-2019

![image](https://user-images.githubusercontent.com/37869674/60342024-f63c4080-99cd-11e9-9514-2759694e7ae9.png)


![image](https://user-images.githubusercontent.com/37869674/60342028-fa685e00-99cd-11e9-84be-ee958503b769.png)

**Comment by parthiban25** [comment]
hi arunchalam

kindly update the latest Deliverables in post shipment commerical 
1..correction
update in Githup

**Comment by badamnarendra028** [comment]
[nsoinvp_comm_2_grd1_gr.zip](https://github.com/astpl1998/Subhasri/files/3385355/nsoinvp_comm_2_grd1_gr.zip)

**Comment by parthiban25** [comment]
hi 
sp is ok..

Latest Design is Update

**Comment by parthiban25** [comment]
hi,

Latest SP Update in Github#36

In postshipment commerical invoice
