### ISSUE TITLE
local tax invoice EDK required in COBI Edit screen

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#15]
hi,

And also refer below screen here also Local invoice option should be there as per below screen here showing only Rebate and Lut:-`send to mail :Sat 1/5/2019 1:25 PM

Action:Receivable management>cobi>edit invoice .required as Local tax invoice EDK Print .View invoice already is there .suppose of any edit it can be view the screen

thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
hi,
Ticked has been raised
by Ramco 
MAG-70791
--



Thanks & regards
Parthiban.R

**Comment by karthikeyanamitysoft** [comment]
ticket raised for Report deliverables ticket id : MAG-70949, once we get deliverables we can move the same to live.

**Comment by parthiban25** [comment]
hi,
solution as 
Can you use in Edit link to view invoice UDS 

Regards
Parthiban.R

**Comment by parthiban25** [comment]
## hi,
solution as
Can you use in Edit screen and bottom of hyperlink  to view invoice UDS
Regards
Parthiban.R
