### ISSUE TITLE
ISS-RTGS (D-cube)

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#151]
pls find the attached the PFS
[RTGS D-cube.zip](https://github.com/astpl1998/Subhasri/files/3328597/RTGS.D-cube.zip)

**Comment by parthiban25** [comment]
RTGS D-cube Report correction has been Done


Beneficiary Name | Amounts | IFSC code | Account No | Debit Account Number | Debit date
-- | -- | -- | -- | -- | --
Chinacoat Exhibition Ltd | 7958.50 |   |   | 03820400000354 | 09/05/2019
Omkar Manpower Services | 256456.00 |   |   | 03820400000354 | 13/06/2019
Total | 264414.50 |   |   |   |

**Comment by badamnarendra028** [comment]
[rtgsss.zip](https://github.com/astpl1998/Subhasri/files/3385309/rtgsss.zip)
