### ISSUE TITLE
ISS - Report Consumption Error Reg

### ISSUE THREAD

**Issue by Duraisingam-G** [astpl1998/Subhasri#158]
Dear Sir,

During report consumption getting error as that "  Conversion failed when converting the nvarchar value 'SPPL_OU' to data type int."
![image](https://user-images.githubusercontent.com/37896999/133238394-49b02bdd-b187-44e3-8e83-85bdb6dfc48b.png)
Kindly allocate to developer to resolve this error on top most priorrity.

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the needful

**Comment by karthikeyanamitysoft** [comment]
clarification provided, ou name mismatched with skm_functiondefaults , prou and with oumaster

**Comment by Duraisingam-G** [comment]
Issue Resolved
