### ISSUE TITLE
ISS-Negative value cannot accept (SUPI-242)

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#16]
hi,

-ve value cannot accept

in Stock ledger report from 31/3/2018 to 30/4/2018

thanks & regards
parthiban.R

**Comment by astpl1998** [comment]
@srinivasanbaskaran Please raise a tkt as discussed without further delay

**Comment by srinivasanbaskaran** [comment]
Ticket has been raised. 

 SUPI-242...

**Comment by parthiban25** [comment]
i have check the ticket still also pending as on 17-4-2019

**Comment by parthiban25** [comment]
march 2019 STOCK  correction not came in negative qty & negative VALUE  for the particular item code
CONS5241 stock qty 22 is available
issue has been resolved

**Comment by parthiban25** [comment]
![image](https://user-images.githubusercontent.com/37869674/56789035-99ca7280-681e-11e9-8987-5a933e2f2519.png)
