### ISSUE TITLE
PPD-Back date should be allowed for all the transaction mentioned

### ISSUE THREAD

**Issue by Harishkanna6** [astpl1998/Subhasri#162]

**Comment by Harishkanna6** [comment]
PFS Completed,Need to be reviewed

[V_1.0_Backdate.Trigger.-PFS.xlsx](https://github.com/astpl1998/Subhasri/files/7725046/V_1.0_Backdate.Trigger.-PFS.xlsx)

**Comment by Harishkanna6** [comment]
@raju-kurup sir

Please find the updated PFS
[Back.date.Trigger.-PFS-v_1.0.xlsx](https://github.com/astpl1998/Subhasri/files/7755433/Back.date.Trigger.-PFS-v_1.0.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please start the development

**Comment by karthikeyanamitysoft** [comment]
Dear Harish,

Kindly create seperate GITHUB ticket for each transaction.

Regards,
Karthi

**Comment by Harishkanna6** [comment]
@karthikeyanamitysoft 

Github id created for each transactions from 178 to 191

closing this ticket , refer the mentioned tickets
