### ISSUE TITLE
PPD- Back date entry for Authorize Inspection Request screen

### ISSUE THREAD

**Issue by Harishkanna6** [astpl1998/Subhasri#183]
@raju-kurup sir,please find the PFS

[Back.date.Trigger.-PFS-v_1.0.xlsx](https://github.com/astpl1998/Subhasri/files/7774560/Back.date.Trigger.-PFS-v_1.0.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please start the development

**Comment by karthikeyanamitysoft** [comment]
Kindly change the PFS and allocate with screen detail and data

**Comment by Harishkanna6** [comment]
Not required
