### ISSUE TITLE
sale order print changes

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#2]
hi,
sale order print changes required

Refer latest PFS & sale order print format

Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,

issue send to karthikeyan
8-1-2019
thanks & regards
Parthiban.R

**Comment by karthikeyanamitysoft** [comment]
given for testing

**Comment by parthiban25** [comment]
hi,
testing completed
fix the old issues
but New changes are required to changes


1 | port of   Discharge | Navigation  sales & shipping>normal sale   order>maintain sale order>take as one transaction   "OC/LC/18-19/294" hyperlink specify shipping Details select Line   level "line 1  multi line  "Destination port "field | New changes
-- | -- | -- | --
2 | customer Grade | Navigation  sales & shipping>normal sale   order>maintain sale order     .Take   transaction "OC/LC/18-19/294" against customer code   :"2B012"item code "FG2506"      Goto sales & shipping>customer >edit customer.enter   "2B012"  bottom hyperlink   edit additional details aganst hyperlink Edit customer item Details that item   "FG2506"item details tab    "customer item code "field populated as "FG25068-52" | not ok
3 | Bag pack | Navigation  sales & shipping>normal sale   order>maintain sale order>take as one transaction   "OC/LC/18-19/294" hyperlink notes :lines level  notes "notes" field | New changes
4 | Pallet pack | More   character enter space available | New changes
5 | MKT Depatch | spelling   mistakes "MKT Despatch" | New changes
6 | Special   instruction | Data   came pls remove | New changes
7 | Rev: | Harcoded   as report top right corner.Data fetching as Navigation sales and shipping   >normal sale order>view sale order >"Amend no"field | not ok
8 | Page 1 of 1 | Report top right   corner edge mention | not ok
9 | continous page | in bottom of report | not ok
10 | Page 2 of 2 | Report top right   corner edge mention | not ok

Thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
hi karthi,
sale order printing issues has been resolved .
sp can be moved from SIM server to Live server

thanks & regards
parthiban.r

**Comment by parthiban25** [comment]
hi,
sale order print issues
![image](https://user-images.githubusercontent.com/37869674/52770607-931ec280-3059-11e9-894b-ad2e019449e9.png)

thanks & regards
Parthiban.R

**Comment by karthikeyanamitysoft** [comment]
Kindly check the issue now in Simulation server
please make sure that the format should not differ, even empty space will affect the data.

**Comment by parthiban25** [comment]
I have check the report same issues

print came:5 kgs per
but actual notes :+1: hdpe Bags 5 kgs per

refer screen shot
![image](https://user-images.githubusercontent.com/37869674/52857452-34d30c00-314d-11e9-8958-479792b3225d.png)
![image](https://user-images.githubusercontent.com/37869674/52857469-42889180-314d-11e9-807d-cd4665844970.png)

**Comment by parthiban25** [comment]
hi,
pls find the same issue in live server
1."Bags pack" field  should be Truncted'
2.Commission type,Bag type is truncted
3.shipping Remarks also only 256 characters available
SOC/EXP/18-19/261
![image](https://user-images.githubusercontent.com/37869674/53102202-350a4780-3551-11e9-9314-3581a551d491.png)
![image](https://user-images.githubusercontent.com/37869674/53102232-43586380-3551-11e9-80b4-f20af30110dc.png)
kindly check 

Regards
parthiban.R
