### ISSUE TITLE
Patch for Expense Invoice

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#23]
hi,

patch for Expense invoice

thanks & regards
parthiban.R

**Comment by karthikeyanamitysoft** [comment]
[supplier_detail.xlsx](https://github.com/astpl1998/Subhasri/files/2844997/supplier_detail.xlsx)

**Comment by karthikeyanamitysoft** [comment]
file attached kindly check

**Comment by girija-s** [comment]
Need Supplier Code against each row of the tax details

**Comment by karthikeyanamitysoft** [comment]
[supplier_detail_gst.xlsx](https://github.com/astpl1998/Subhasri/files/2845018/supplier_detail_gst.xlsx)

**Comment by girija-s** [comment]
[Expenses Patch Transaction List.xlsx](https://github.com/astpl1998/Subhasri/files/2864975/Expenses.Patch.Transaction.List.xlsx)

Dear Karthi
Please allocate this to Jeyapriya as she has already applied patch for Account code Correction for GSTPINPUTTAX

**Comment by karthikeyanamitysoft** [comment]
Dear Jeyapriya kindly do the data correction

**Comment by girija-s** [comment]
[Expenses Patch Transaction List.xlsx](https://github.com/astpl1998/Subhasri/files/2878603/Expenses.Patch.Transaction.List.xlsx)

Jeyapriya 

Updated the FBP transaction no. Pls go update the patch now also run the fb region

**Comment by Jeyapriyat** [comment]
@girija-s 
  
patch and regin run in simulation server,kindly check and revert

**Comment by venkateshk7** [comment]
Dear mam.
                completed patch testing in simulation server and found correct.

**Comment by girija-s** [comment]
Dear Jeyapriya,

Please run the patch in liver server and provide the rtrack no in GITHUB

**Comment by Jeyapriyat** [comment]
@girija-s 
i have attache rtrack no : MAG-72769

**Comment by girija-s** [comment]
Dear Jeyapriya

Pls attach the patch in GITHUB

**Comment by raju-kurup** [comment]
Issue resolved
