### ISSUE TITLE
ISS-Agent commission required in sale order

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#28]
Agent commission is required as sale orde level for based on Actual price & value can captured and reflected as invoice level
solution as
Sales persons consider as agent name and mapping at the time of sale order creation for % & Value
Required as report level will reflected the commission amount

Thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,

I have modeling the  Agent commission In Subhasri UAT Server


thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
HI,
Rtrack ticket raised to Ramco-SUPI-233

Regards
parthiban.R

**Comment by astpl1998** [comment]
Solution given to customer
