### ISSUE TITLE
ISS-Credit Management to be implemented at Packslip stage

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#30]
packslip (outstanding) customer is blocked
overdue can be blocked the amount
for ex:credit limit exceed 50000
for 0 to 90 days
it will block the customer

thanks & regards 
parthiban.R

**Comment by parthiban25** [comment]
hi,

credit management training to jignesh and Document also send

[Credit Management.zip](https://github.com/astpl1998/Subhasri/files/2864563/Credit.Management.zip)


Thanks & regards
parthiban.R

**Comment by astpl1998** [comment]
Email of the document send to Jignesh.
