### ISSUE TITLE
sale order Export print is required

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#31]
New requirement

sale order Export print 
1.Export print is required(format )
2..print special remarks maximum 18 lines
3..changes in sale order consignee name,special remarks,shipping remarks,internal grade,400 lines required in print
sale order required to extended as 7 items and 7 different lot
![sale order export print](https://user-images.githubusercontent.com/37869674/52109792-ac208000-2624-11e9-8b97-99bee9b9f67f.jpeg)

**Comment by karthikeyanamitysoft** [comment]
completed

**Comment by parthiban25** [comment]
solution   both export & local in one print
--

**Comment by parthiban25** [comment]
hi
Packing material created in live server

Regards
Parthiban.R

**Comment by parthiban25** [comment]
## solution both export & local in one print

**Comment by parthiban25** [comment]
## solution both export & local in one print
