### ISSUE TITLE
ISS-Email Alert not working for workflow (SUPI-234)

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#33]
hi,

E-mail   alert configuration Done in UAT & live server
--

**Comment by parthiban25** [comment]
hi, 

Email alert not working in purchase order 
Navigation 
Tools>workflow>Enable Notification message 

purcahase order >create Direct purchase order >authorized of PO-create po 

click and enable notification message 
already configuration is Done 
and select and click user identification all are Done 
But purchase order Created in fresh status mail send to particular user name not working 
kindly update is issue 

Thanks & regards
Parthiban.R

**Comment by astpl1998** [comment]
Ramco is asking for Email Log file

**Comment by parthiban25** [comment]
Still also Pending with Ramco E-mail alert

**Comment by parthiban25** [comment]
issue resolved by Ramco .

E-mail alert is working
