### ISSUE TITLE
ISS-ALL DELIVERABLES

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Subhasri#36]

**Comment by srinivasanbaskaran** [comment]
All Customization List & PFS are attached... 
[Subashri (Full) Final customization list1 (2).xlsx](https://github.com/astpl1998/Subhasri/files/2871693/Subashri.Full.Final.customization.list1.2.xlsx)

**Comment by srinivasanbaskaran** [comment]
Lastest deliverables to be added for Local Invoice DW Report.

**Comment by srinivasanbaskaran** [comment]
Attached all latest deliverables...

[Subashri (Full) Final customization list1 (2).xlsx](https://github.com/astpl1998/Subhasri/files/2887870/Subashri.Full.Final.customization.list1.2.xlsx)

**Comment by srinivasanbaskaran** [comment]
Parthiban,

Kindly follow up with developers & get all the Latest Deliverables

Thanks & Regards,

Srinivasan Baskaran

**Comment by parthiban25** [comment]
15/7/2019 & 16/7/2019

some D-cube report not available in PFs 

Maintain Gate Entry screen also not available any records & Design

[Subhasri customization Report as on   9-7-2019.zip](https://github.com/astpl1998/Subhasri/files/3400295/Subhasri.customization.Report.as.on.9-7-2019.zip)

Updated  Deliverables also pending

**Comment by parthiban25** [comment]
hi srini,

pls find the attached the Latest Deliverables from all customization Report and D-cube Report
mentioned in Remarks and Status closed means all Deliverables come in Excel in object  "H" Field
pending as blank sp & object any one 

[Subhasri customization Report as on   9-7-2019.zip](https://github.com/astpl1998/Subhasri/files/3471828/Subhasri.customization.Report.as.on.9-7-2019.zip)

**Comment by parthiban25** [comment]
hi srini,
pls find the attached latest Deliverables from all customization Report 

Ramco send the File as on 17-9-2019

[Subhasri customization Report 01 as on   9-7-2019.zip](https://github.com/astpl1998/Subhasri/files/3620712/Subhasri.customization.Report.01.as.on.9-7-2019.zip)
[Subhasri customization Report 01 as on   9-7-2019.zip](https://github.com/astpl1998/Subhasri/files/3621138/Subhasri.customization.Report.01.as.on.9-7-2019.zip)
