### ISSUE TITLE
ISS-Raw material stock mismatching the ramco and tally 

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#37]
Dear Concerned Amitysoft Member.

Regret to inform you the attached sheet are the details of Raw Material OP Balance as on 31.03.18 not matching with Ramco, request you to kindly do the necessary at the earliest to overcome the difficulties.

thanks & regards
Parthiban.R

**Comment by raju-kurup** [comment]
Subhasri has certified and asked us to close the financial closure in ERP for the FY 2017-18 vide mail dt 13.03.2019 by Mr.Basant
