### ISSUE TITLE
Supplier Balance Adjustment

### ISSUE THREAD

**Issue by girija-s** [astpl1998/Subhasri#38]
Supplier Balance Adjustment Need to be created for the date 31.3.18 as a part of TB Correction FY17-18.

**Comment by venkateshk7** [comment]
Dear mam 
supplier balance adjustment completed  red color date is not matched. amount is not fetching. green color completed 

[Supplier Reference Document.xlsx](https://github.com/astpl1998/Subhasri/files/2855554/Supplier.Reference.Document.xlsx)

**Comment by raju-kurup** [comment]
Issue resolved
