### ISSUE TITLE
Customer Balance Adjustment

### ISSUE THREAD

**Issue by girija-s** [astpl1998/Subhasri#39]
Dear Venkatesh

Please Create & Authorize Customer Balance Adjustment as on 31.3.18 as  a  part of TB correction Work as on 31.3.18

**Comment by venkateshk7** [comment]
Dear girija mam

green coler completed ,read coler amount not fach & date deferant

Regads 
M.venkatesan

**Comment by venkateshk7** [comment]
Dear girija mam
green coler completed ,read coler amount not fach & date deferant

**Comment by venkateshk7** [comment]
[Customer Sub Ledger - Tran Curr - Details  - 31.3.18.zip](https://github.com/astpl1998/Subhasri/files/2844678/Customer.Sub.Ledger.-.Tran.Curr.-.Details.-.31.3.18.zip)
dear Mam,

File attcehd in that ZIP file
