### ISSUE TITLE
ISS-Tax is not calculated in SOBI.

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#44]
hi,  
supi-236
SOBI as Not update in TAX 

While click the tax account code not Defined for input combination error" 
but check in GRN It is TAX calculated and purchase also TAXcalculated. 
so purchase order TRD is calculated but TAX code not updated in PO,GRN 
.Kindly update PO,GRN ,Invoice it is changes as Fresh Status 

Invoice no: SP/IN/ST/18-19/847 
purchase return no: SP/RTGR/18-19/105 
Debit note no: IT_DBNT/18-19/0102 
GRN No: SP/GRNGN/18-19/890 
purchase order No: SPPL/GN/18-19/868 

Thanks & regards
Parthiban.R

![image](https://user-images.githubusercontent.com/37869674/52837389-91660500-3114-11e9-8da6-84b3eef2fb5e.png)

**Comment by girija-s** [comment]
Parthi,

Checked the configuration. ARD is available for all the tax group and tax % for the mentioned tax category and tax class
but in GR there is no tax posting and hence that error is coming.
Here the items are mapped to different tax group. 

Please try the same sequence in simulation server and check

**Comment by parthiban25** [comment]
Ticket Reopen SUPI-236
