### ISSUE TITLE
purchase return note charges not Reverse

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#45]
hi,
supi-235
Purchase return note charges  not Reverse
total as 720
problem as charges 95
total amount is 720 +18%
720+129.60=849.60
but missing in 95 Rs.
Required amount Debit as 962.00
in ramco system as 849.60

supplier :SPPL/SUPP/0362
invoice no:SP/IN/ST/18-19/891
GRN:no :sppl/gn/18-19/910
purchase return note no:SP/RTGR/18-19/111
Debit note no:IT_DBNT/18-19/0108

Thanks & regards
Parthiban.R

**Comment by raju-kurup** [comment]
Issue resolved.
