### ISSUE TITLE
Changes invoice Number in GRN

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#46]
hi,
Please find below details for change Invoice number in GRN:-
Ref. Doc. Date | Ref. Doc. No. | Name | Old Bill no | Delivery Note Date | Entered Wrong Invoice No. | Correct Invoice no | Supplier Invoice Date
-- | -- | -- | -- | -- | -- | -- | --
15/12/2018 | SP/GRNRM/1819/1043 | Shreegopal   Celluchem Pvt.Ltd | 496 | 15/12/2018 | 496 | 496/GST | 15/12/2018

Thanks & regards
Parthiban.R

**Comment by girija-s** [comment]
Dear Parthi

Rtrack raised for the above -  MAGna ticket no MAG-72426

you can check the status of the ticket tomorrow and check the correction happened in live server

**Comment by parthiban25** [comment]
Issue has resolved MAG-72426
Patch Deployed in live server
