### ISSUE TITLE
ISS-Inventory correction for  april month  2018

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#49]
Inventory Correction For April month 2018
Pls find the Attached For Tally and ramco mismatching
[Copy of Tally RM Stock  april-18 (4).zip](https://github.com/astpl1998/Subhasri/files/2871685/Copy.of.Tally.RM.Stock.april-18.4.zip)

Thanks & regards
parthiban.R

**Comment by srinivasanbaskaran** [comment]
Hi Team,

We are doing the comparison only on April 2019.

**Comment by parthiban25** [comment]
correction file
[Copy of Subhasri Comparism  xlsx (4).zip](https://github.com/astpl1998/Subhasri/files/3042280/Copy.of.Subhasri.Comparism.xlsx.4.zip)
