### ISSUE TITLE
Schedules to income statement

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#50]
From ramco below list Breakup Required
This is Schedules to income statements
1.Revenue from operations
2.other income
3.costs of Goods
4.Employee benefits expense
5.Finance costs
6.other Expenses

![image](https://user-images.githubusercontent.com/37869674/52898248-918ffe80-3201-11e9-9b46-ac56b1468906.png)

Reagards
Parthiban.R

**Comment by girija-s** [comment]
Book Keeping > REports on Book Keeping > Report on Income Statement > Select the financial year & financial Period and click the sub schedule to Income Statement.
