### ISSUE TITLE
ISS-April Month MR issues Packing and consumables

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#51]
hi,
pls find the attached for April month 2018 with Ramco item code
MR issues
1.Packing
2.consumable

[april month Details 2018.zip](https://github.com/astpl1998/logistics/files/2884371/april.month.Details.2018.zip)

**Comment by parthiban25** [comment]
hi 

April month Consumable 2018  missing item code is updated

[Copy of Tally Issue Details 01042018 to 30042018.zip](https://github.com/astpl1998/Subhasri/files/2888679/Copy.of.Tally.Issue.Details.01042018.to.30042018.zip)

**Comment by girija-s** [comment]
Dear Parthi

PFA Packing Material Issue List for April18 Reconciliation statement. for the difference subhasri has to make the necessary entries in ramco.

**Comment by girija-s** [comment]
File Attached
