### ISSUE TITLE
ISS-Rebate invoice print issue

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#53]
Rebate invoice
navigation Reveivable management>COBI>View invoice 1819100256

1.margin border is cutting in right align
2.Authorized signature it will goes to second screen(pls required in first screen)
3.Details of Receiver (billed to)
loggic 
Name Field:Goto sales & shipping>Customer >EDit customer>Edit additional details>.General information Tab"identification No" 
4.Details of Consignee(shipped to)
Name Field:Goto sales & shipping>Customer >EDit customer>Edit additional details>.General information Tab"Export Registration no" 
5.Description of Goods ,HSN,No of PKG .can you use the any special character.clarified in Skype

![image](https://user-images.githubusercontent.com/37869674/53390287-b2521400-39b8-11e9-916e-a4c0754f5b53.png)

Regards
Parthiban.R

**Comment by karthikeyanamitysoft** [comment]
there is no record available

**Comment by parthiban25** [comment]
testing completed
1.marign border -->resolved
2.Authorized signature -->resolve
3.Details of Receiver (billed to)-->resolve
4.Details of Consignee(shipped to)--> resolve
5.Character * is added -->resolved

kindly sp move to live server

Thanks & regards
parthiban.R

**Comment by karthikeyanamitysoft** [comment]
[taxri_print__grd1_gr.zip](https://github.com/astpl1998/Subhasri/files/2921779/taxri_print__grd1_gr.zip)
modified sp attached

**Comment by parthiban25** [comment]
i am already testing in sim server.kindly move to live server

**Comment by parthiban25** [comment]
hi
while click the print system throw error"

SELECT failed because the following SET options have incorrect settings: "QUOTED_IDENTIFIER". Verify that SET options are correct for use with indexed views and/or indexes on computed columns and/or filtered indexes and/or query notifications and/or XML data type methods and/or spatial index operations."
--

kindly resolved the issue

![image](https://user-images.githubusercontent.com/37869674/54338339-99ec2580-4657-11e9-8ce6-9c80d18f283a.png)

**Comment by karthikeyanamitysoft** [comment]
[sp.zip](https://github.com/astpl1998/Subhasri/files/2983202/sp.zip)
issue solved and raised rtrack to move the attached deliverables to live.

**Comment by karthikeyanamitysoft** [comment]
MAG-75039

**Comment by parthiban25** [comment]
hi,
Error came in live server
![image](https://user-images.githubusercontent.com/37869674/54801623-c1fa0b00-4c8d-11e9-8932-1096e1150f89.png)

**Comment by parthiban25** [comment]
Kindly update the Print Rebate invoice

**Comment by parthiban25** [comment]
I have check in Sim server 
1.(*)symbol used Data not came
![image](https://user-images.githubusercontent.com/37869674/54806719-e4e1ea80-4ca0-11e9-8ec2-a19d74d5530d.png)

**Comment by parthiban25** [comment]
issue has been resolved
