### ISSUE TITLE
DEV-LUT invoice print issue

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#54]
lut invoice
1.navigation Receivable management>COBI>View invoice . 1819100253 ( in the print 
Rate ,value column as empty) and also total amount ,final amount also missing

2.Same LUT print
navigation Receivable management>COBI>View invoice . 1819200259 ( in the print  all Details are came)

3.margin border is cutting in right align
4.Authorized signature it will goes to second screen(pls required in first screen)
5.Details of Consignee(shipped to)
Name Field:Goto sales & shipping>Customer >EDit customer>Edit additional details>.General information Tab"Export Registration no"
6.Description of Goods ,HSN,No of PKG .can you use the( * ) special character .clarified in Skype

pls Refer the Rebate invoice 

Regards
Parthiban.R

**Comment by parthiban25** [comment]
lut invoice
1.navigation Receivable management>COBI>View invoice . 1819100253 ( in the print 
Rate ,value column as empty) and also total amount ,final amount also missing
2.Details of Consignee(shipped to)
Name Field:Goto sales & shipping>Customer >EDit customer>Edit additional details>.General information Tab"Export Registration no"
3.Description of Goods ,HSN,No of PKG .can you use the( * ) special character .clarified in Skype

![image](https://user-images.githubusercontent.com/37869674/54337918-63fa7180-4656-11e9-8a80-56b05df01dbf.png)
regards

parthiban.R

**Comment by parthiban25** [comment]
hi ,

issue has been resolved in Sim server refer in screen shot
SP move to Live server
![image](https://user-images.githubusercontent.com/37869674/54603565-a95ddb00-4a6a-11e9-8c72-76e5c0c19faa.png)


Regards
Parthiban.R

**Comment by karthikeyanamitysoft** [comment]
Issue solved, sp attached and raise rtrack MAG-75100 to move the deliverables in to live.
[lut_invoice.zip](https://github.com/astpl1998/Subhasri/files/2983211/lut_invoice.zip)

**Comment by parthiban25** [comment]
hi,
Ticket is Deployed  in Live server .but Error came live server

navigation\

Receivable management>COBI>view invoice>1819200498 UDS as LUT print click the print system throw error"

SELECT failed because the following SET options have incorrect settings: "QUOTED_IDENTIFIER". Verify that SET options are correct for use with indexed views and/or indexes on computed columns and/or filtered indexes and/or query notifications and/or XML data type methods and/or spatial index operations."
--
kidly resolve the issue

![image](https://user-images.githubusercontent.com/37869674/54665449-1cb82900-4b0d-11e9-8661-9c58cded89b5.png)

**Comment by parthiban25** [comment]
kindly update the LUT print invoice

**Comment by parthiban25** [comment]
i have check in sim server 

same error came
![image](https://user-images.githubusercontent.com/37869674/54806774-10fd6b80-4ca1-11e9-9821-9329b9de557f.png)

**Comment by parthiban25** [comment]
this issue is Resolved
