### ISSUE TITLE
ISS-sale order print issue

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#57]
hi,

In sale order print  More Space required in Special remarks column Field

Regards
Parthiban.R

**Comment by parthiban25** [comment]
issues has been resolved
Testing completed latest  SP moving to LIve server

**Comment by karthikeyanamitysoft** [comment]
Ticket moved MAG-73174

**Comment by raju-kurup** [comment]
Issue closed by getting confirmation from Jignesh.

**Comment by parthiban25** [comment]
hi,

kindly update the  Latest sp &   Design 
--

**Comment by parthiban25** [comment]
hi,
pls check the Githup#36

All Deliverables attached
