### ISSUE TITLE
ISS-GR Register-(SUPI-237)

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#62]
GR register
Report not launching in Live server

I have been select the report Document type as GR Register and next filter select as receipt from and to Date 
Next selected as shown invoice info enable click the print report as launched Blank . 
refer the screen shot
Attachments

**Comment by raju-kurup** [comment]
Ramco pendin

**Comment by parthiban25** [comment]
issue has been resolved

**Comment by astpl1998** [comment]
Ramco resolved this issue
