### ISSUE TITLE
Subhasri Finance - KT

### ISSUE THREAD

**Issue by astpl1998** [astpl1998/Subhasri#79]
@

**Comment by astpl1998** [comment]
@basha123456   Please update the MOM of KT sessions in this TKT

**Comment by basha123456** [comment]
[Subhasri TB Correction KT.xlsx](https://github.com/astpl1998/Subhasri/files/3021871/Subhasri.TB.Correction.KT.xlsx)

Dear All,

Please find the attached KT of Subhasri TB correction of 28.03.2019.

Regards,
Basha

**Comment by astpl1998** [comment]
@girija-s Pl train @basha123456 in Period closing while your doing the March 2018 closure

**Comment by girija-s** [comment]
Dear Badsha

As discussed pls do the necessary correction in the MOM.
Please add the customer and Supplier also

Regards
Girija

**Comment by srinivasanbaskaran** [comment]
Finance Knowledge Transfer Completed... 


Hence, This ticket has been closed....
