### ISSUE TITLE
USD to INR Conversion

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#8]
hi,

USD to INR Conversion ( From EEFC 1627 $ A/c to 354 OD A/C INR )
 
D.24.09.2018 $ 81,549 * Rs.72.49001 ( per $ ) = Rs.59,11,488
mail to amity from jignesh  as on Wed, Dec 26, 2018 at 1:46 PM

Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
hi,
Detail send to Girija madam 9-1-2019
Status:as in progress

 Thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
hi ,
mail send to ramco 
Dear Viji,

RTrack ID : SUPI-232

Subhasri is transferring amount from our EEFC Bank A/c No:1627 in USD currency to our CC A/c 0354 in INR.  We are not able to do the transaction due to the receiving bank in multiline shows only USD account banks instead of INR account banks after selecting USD bank in the header of Bank cash transfer transaction.

This type of transaction is regular for their business scenario.  Please resolve this in high priority and due to this many voucher are pending to feed in ERP.

thanks & regards
parthiban.R

**Comment by raju-kurup** [comment]
Work around given and recitification needed from ramco, ticket raised
