### ISSUE TITLE
ISS-Final TB Correction for Ramco upto March 2018

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#9]
Mail raised to Girija Madam
Awaiting for the Inventory Balances to start the TB correction Activity. Kindly Provide the Inventory Details as on 31.3.18 (Refer our earlier Mails)

Thanks & regards
Parthiban,R

**Comment by parthiban25** [comment]
Hi,
jignesh send TB File send to Girija madam from amity
Madam,

PFA Item wise stock details for TB upload activity.

NOTE:-File have no. of sheets so please check accordingly.
mail Details: Fri 1/4/2019 4:59 PM

thanks & regards
parthiban.R

**Comment by parthiban25** [comment]
hi,
Girija madam reply to jignesh clarification required mail send to Sat 1/5/2019 4:07 PM
1. On Analyzing the Customer & Supplier Bill wise breakup with your TB, the following accounts are not matching with your TB.  Please clarify the below differences
Local Customer Code	Customer Name 	Balance as per Bill wise Breakup	Balance As per your TB	Difference
2B012	Magnus Colours	3206	0	3206
2D043	Subhasri Pigments Pvt Ltd{Unit-II}- Debtors	768291.7	-813547.46	1581839.16

2.Supplier Balance Difference between bill wise breakup & TB


			
SUPPLIER CODE	AS PER SUBHASRI	DIFFERENCE
	BILLWISE BREAKUP	TRIAL BALANCE -  SUPPLIER BALANCE	
SPPL/SUPP/0015	56492.45	-56492.36	                    0.09 
SPPL/SUPP/0114	1752810.56	-1752810.86	                 (0.30)
SPPL/SUPP/0119	24250	0	         24,250.00 
SPPL/SUPP/0204	125633.21	-145633.96	       (20,000.75)
SPPL/SUPP/0290	93494	0	         93,494.00 
SPPL/SUPP/0461	336595	-351491	       (14,896.00)
SPPL/SUPP/0471	8100	-56600	       (48,500.00)
SPPL/SUPP/0551	266476	-398476	    (132,000.00)
SPPL/SUPP/0634	1319332.5	-1769557.5	    (450,225.00)
SPPL/SUPP/0715	23140	-60270	       (37,130.00)
SPPL/SUPP/0730	9604324.18	0	   9,604,324.18 
SPPL/SUPP/0745	-122	121.52	                 (0.48)
SPPL/SUPP/0746	5996	-5996.22	                 (0.22)
SPPL/SUPP/0785	308995	-285206	         23,789.00 
SPPL/SUPP/0814	323421	-80421	       243,000.00 
SPPL/SUPP/0844	109096	0	       109,096.00 
SPPL/SUPP/0860	108575	-217671	    (109,096.00)
SPPL/SUPP/0918	6169850	-6587350	    (417,500.00)
SPPL/SUPP/0935	244428.8	-207298.8	         37,130.00 
SPPL/SUPP/0936	13796	1100	       (12,696.00)
SPPL/SUPP/0945	357530	0	       357,530.00 
SPPL/SUPP/0988	356474	0	       356,474.00 
SPPL/SUPP/0989	1151758	0	   1,151,758.00 
SPPL/SUPP/0991	-352800	0	    (352,800.00)
SPPL/SUPP/0992	31353	-16353	        15,000.00 
SPPL/SUPP/1006	968000	-640200	       327,800.00 
SPPL/SUPP/0024	 	-243000	    (243,000.00)
SPPL/SUPP/0090	 	-93494	       (93,494.00)
SPPL/SUPP/0696	 	354962.75	       354,962.75 
SPPL/SUPP/0702	 	65567	         65,567.00 
SPPL/SUPP/0820	 	41778	         41,778.00 
SPPL/SUPP/0996	 	3564.5	           3,564.50 
SPPL/SUPP/1033	 	-357530	    (357,530.00)
thanks & regards
Parthiban.R

**Comment by parthiban25** [comment]
hi, Girja madam clarification required mail send to jignesh 8-1-2019
Analyzed the Supplier Bill wise Breakup with the Trial Balance, the following Supplier bill wise breakup not matching with the Trial Balance. Please Clarify
 
Supplier Code	Supplier Name	Supplier Bill Wise BreakUp	Supplier Balance as per Trial Balance	Difference 
SPPL/SUPP/0156	Synersoft Technologies Pvt Ltd	4860	4860	              9,720.00 
SPPL/SUPP/0290	AUTO LINK	93494	0	           93,494.00 
SPPL/SUPP/0684	G.E.B. - 5903	25943.23	25943.23	           51,886.46 
SPPL/SUPP/0730	ANJANEYA CHEMICALS	9604324.18	0	     9,604,324.18 
SPPL/SUPP/0844	AISHWARYA ENGINEERING [PRO]	109096	0	         109,096.00 
SPPL/SUPP/0945	WITS INTERACTIVE PVT LTD	357530	0	         357,530.00 
SPPL/SUPP/0992	Gift  Vision	31353	-16353	           15,000.00 
Grand Total	 	10226600.41	14450.23	   10,241,050.64 
 
 
For the Following Supplier Bill wise breakup not provided. Please provide / Clarify
 
Supplier Name	Supplier Code	Supplier Balance As per TB
SPPL/SUPP/0028	Citibank Card No.4386 2800 1401 9677	667.85
SPPL/SUPP/0090	Auto Link	-93494
SPPL/SUPP/0369	Matrix Networks & Solutions	-23810
SPPL/SUPP/0696	Bharuch Enviro Infrastructure Ltd	354962.75
SPPL/SUPP/0755	Shree Chem	-233819.5
SPPL/SUPP/0763	V.Vedamanickam	-106200
SPPL/SUPP/0815	Gujarat Industrial Development Corporation	-81077
SPPL/SUPP/0862	Aditya Chemicals Broker	-3544
SPPL/SUPP/0990	Coffee Day Global Limited	26000
SPPL/SUPP/0996	Bharuch Enviro Infrastructure Ltd for U2	3564.5
SPPL/SUPP/1013	AADITYA CHEMICALS (New)	-287995
SPPL/SUPP/1031	Sundry Creditor Others Import	-171057811.5
SPPL/SUPP/1033	Wits Interactive Pvt Ltd	-357530
Grand Total	-171860085.9
 
Kindly do the Needful at the earliest
 
Thanks and Regards
Parthiban.R

**Comment by parthiban25** [comment]
Girija Madam mail send to jignesh Clarification 10-1-2019

Dear Jignesh,
 
On Analyzing the Customer & Supplier Bill wise breakup with your TB, the following accounts are not matching with your TB.  Please clarify the below differences
 
Local Customer Code	Customer Name 	Balance as per Bill wise Breakup	Balance As per your TB	Difference
2B012	Magnus Colours	3206	0	3206
2D043	Subhasri Pigments Pvt Ltd{Unit-II}- Debtors	768291.7	-813547.46	1581839.16
 
PFA the Trail Mail(5-1-19) requesting for the above details

Thanks & regards
Parthiban.R

**Comment by astpl1998** [comment]
Meeting 19-02-19 
[Subhari-cogs.xlsx](https://github.com/astpl1998/Subhasri/files/2884537/Subhari-cogs.xlsx)
[Subhasri-TB-Reconcilation.xlsx](https://github.com/astpl1998/Subhasri/files/2884538/Subhasri-TB-Reconcilation.xlsx)

**Comment by astpl1998** [comment]
Meeting 20-02-19
- Closing balance 31-02-18 and Opening Balance of 01-04-18 to reconciled and differences to be sorted out
- Purchase of Apl of tally and ERP to be reconciled and differences to be sorted out 
- COGS Explanation done and file attached 
[Subhari-cogs.xlsx](https://github.com/astpl1998/Subhasri/files/2884791/Subhari-cogs.xlsx)

**Comment by astpl1998** [comment]
Meeting 20-02-19  comments updated

**Comment by astpl1998** [comment]
Meeting 21-02-2019

COGS explained by Parthi to Mr Chary and be nas principally accepted 

The importance of reconciling stocks higlighted to Parthi should take up the below tasks on top most priority 
 
* Closing balance 31-03-18 and Opening Balance of 01-04-18 to reconciled and differences to be sorted out
* Purchase of Apl of tally and ERP to be reconciled and differences to be sorted out

**Comment by astpl1998** [comment]
Meeting 25-02-2019
- Add 20000 in Packing material
- Clarify 12500 of Packing material in consummable 
- compare ramco value with the latest consumable file provided diff entry to be passed
- GET list of purchases and compare
- Compare issue list with tally issues
- Retained earnings Girija will clarify

**Comment by parthiban25** [comment]
hi,
April month 2018  MR issue consumable and packing list subhasri Tally
[april month Details 2018.zip](https://github.com/astpl1998/Subhasri/files/2900521/april.month.Details.2018.zip)

Regards
parthiban.R

**Comment by parthiban25** [comment]
hi,
march month 2018 latest consumable and packing correcting and finalized by Besant
[Besant file march 2018.zip](https://github.com/astpl1998/Subhasri/files/2900640/Besant.file.march.2018.zip)


Thanks & regards
parthiban.R

**Comment by astpl1998** [comment]
Meeting 26-02-2019
- Currently stock differences reconcilation is difficult for Subhasri reconcilation of Stocks is put to hold
- So Expenses and revenues need to be reconciled and differences to be provided tomorrow
-

**Comment by raju-kurup** [comment]
pending is inventory updating, once closed we want to get confirmation and certification from Subhasri

**Comment by srinivasanbaskaran** [comment]
[Consumables  31 03 18  -  Corrections (2)-Girija.xlsx](https://github.com/astpl1998/Subhasri/files/2944669/Consumables.31.03.18.-.Corrections.2.-Girija.xlsx)
[Stk Correction.xlsx](https://github.com/astpl1998/Subhasri/files/2944681/Stk.Correction.xlsx)

**Comment by raju-kurup** [comment]
Subhasri confirmed and to close the financial book vide email by Mr.Basant.
