### ISSUE TITLE
ISS-GRN User interface print issue

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#90]
Report against IGST Value Came as Wrong

Refer Screen Shot
PMGR/1920/0012
Logic 
case 1:view tax calculation summary --->Tax code is available "corrected Tax amount " Dispaly
case 2:view tax calculation summary-->tax code is not available click view tax calculation -Details click refeDoc.no :1 "Tax code "against corrected tax amount added ,+ ref doc.no:2 Tax code against corrected Tax amount.(what ever it is SGST is added,CGST Is added and IGST added separately)

![image](https://user-images.githubusercontent.com/37869674/56186776-32ead380-603e-11e9-8562-e9e99c54a8eb.png)

**Comment by parthiban25** [comment]
hi 
Refer the transaction PMGR/1920/0012  print IGST value came wrong 
system IGST-19968.62(correct)
but print shown as-39337.24(it is wrong)

![image](https://user-images.githubusercontent.com/37869674/57758001-5627a200-7714-11e9-8ae6-00f50d37a95c.png)

**Comment by parthiban25** [comment]
GRN testing issues
Refer GRN PMGR/1920/0012 pending qty should have been wrong came in print
![image](https://user-images.githubusercontent.com/37869674/58075657-de4ef100-7bc5-11e9-9572-f2babbc32ca1.png)
![image](https://user-images.githubusercontent.com/37869674/58075666-e444d200-7bc5-11e9-87de-7402200af7bc.png)

**Comment by parthiban25** [comment]
issue has been resolved 
Mail to jignesh
as on 22/5/2019

[GRN print001.pdf](https://github.com/astpl1998/Subhasri/files/3205712/GRN.print001.pdf)

**Comment by parthiban25** [comment]
previous issue has been resolved
Added the two points
as on 22/5/2019
Also one query raised by our Director Sh. KS that instead of SUBHASRI PIGMENTS PVT. LTD. along with all details should be come Supplier details & SUBHASRI PIGMENTS PVT. LTD print as a heading.

**Comment by parthiban25** [comment]
GRN Print IGST value are correct & parallel check the CGST/SGST
Attached for sample
PMGR/1920/0012
![image](https://user-images.githubusercontent.com/37869674/60566903-f6e62580-9d85-11e9-95da-75dc36885536.png)
![image](https://user-images.githubusercontent.com/37869674/60566912-01082400-9d86-11e9-8a30-45ab8343e59e.png)
![Uploading image.png…]()

**Comment by parthiban25** [comment]
hi,
Design is ok..
Update the latest SP

**Comment by raju-kurup** [comment]
Issue resolved and Ticket raised to Ramco - MAG-89133
