### ISSUE TITLE
ISS-preshipment proforma invoice

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/Subhasri#93]
hi ,
print issues as on 23-4-2019

1.Attach notes Data came three times .they required as single time at the Description of Goods 
next times
for example:
case 1:one item 3 line came and next line attach notes came
case 2:two different item and next line attach note came
![image](https://user-images.githubusercontent.com/37869674/56565134-4a413800-65cd-11e9-967e-fb8da7e6bc94.png)
![image](https://user-images.githubusercontent.com/37869674/56565354-ccc9f780-65cd-11e9-825b-a026206e0613.png)

**Comment by parthiban25** [comment]
latest update issue as on 21-5-2019

1.Add   one print Address Changes (customs)must .remaining Data are Refer Existing   Report     2.consignee & buyer as line by line no space is required suppose Empty   Data as Merge showing in Report      
3.SPPL45D -->Remove data     
4.Qty,Rate Amount   Line Required   Refer screen shot    
 5.Repeated the Data is wrong only Enter in Last Data of invoice  
   6.More space is required B/w Data and total Amount     
7.print format size is Decrease because of stapler is print Data is   hidden    
 8. Every page Header & footer  is   Required.page number Required    
 9.case 1:one line item multiple Grade & pallets it will come next to   next line come refer screen shot     10.case 2:Two line item Different Grade & pallets it will come Correct   Line  Required
Refer Attchement
[2.preshipment.zip](https://github.com/astpl1998/Subhasri/files/3201731/2.preshipment.zip)

--

**Comment by parthiban25** [comment]
Testing issue in live server as on 28/5/2019
1.refer screen shot one page number is truncated
2.refer screen shot two quantity ,rate amount two times came
refer screen shot two that horizontal  line remove from all page
3.refer screen shot Three  that marks ,no.of kinds,good description quantity,rate,amount
![image](https://user-images.githubusercontent.com/37869674/58452302-7bfd6f80-8134-11e9-9605-85a36c3db664.png)

![image](https://user-images.githubusercontent.com/37869674/58452303-7e5fc980-8134-11e9-8835-00cb18825d00.png)

![image](https://user-images.githubusercontent.com/37869674/58452306-83bd1400-8134-11e9-80cc-dc624d7143f6.png)

**Comment by parthiban25** [comment]
Preshipment  proforma invoice

Two Print as Completed pls note it as following procedure
1.preshipment proforma invoice (insurance )refer Screen shot 1,2 &5  put as input transaction no:1920100013
2.preshipment proforma invoice (customs)refer screen shot 3,4 & 6 put as input transaction no: 1920100013-C   for every packslip for customs  using (-C)
Refer attach the shortcut key for updated

Attached Note :
Template
<pre carriage by >RAIL
<vessel/flight no>ABCD12345/ER
<DRAWBACK TARIFF CODE>320499 (B)
<HS CODE NO> 32041761
<EXPORT SCHEME>SHIPMENT UNDER DUTY DRAWBACK SCHEME

<Tax Detail>DRAWBACK TARIFF CODE : 320499 (B)
HS CODE NO.: 32041761
EXPORT SCHEME : SHIPMENT UNDER DUTY 
DRAWBACK SCHEME
PAN No.: AABCS1337G
IEC Code No.: 0395064252 
GST No.: 24AABCS1337G1ZR
Shipping Bill No. & Date.: 
Bill of Lading No. & Date.:
<4> We intend to claim rewards under Merchandise Exports from India Scheme (MEIS).
<5> Exports made under EPCG scheme, against EPCG license no. 0330048767 Dt. 22.02.2018 & 0330049431 Dt.19.06.2018.

<net>total  Net Weight :1,kgs
<Gross>total Gross weight :11kgs
<pallet>Total pallets:02 pallets

<Freight>fright:USD
<Ins>insurance USD
<FO>FOB: USD
<1>The goods are covered under post shipment DBK scheme SR.no3204998
<2>we shall claim Drawback after availement input tax facility under ITC rules 2017

<3>Export scheme:shipment under Drawback scheme

![image](https://user-images.githubusercontent.com/37869674/60658602-2a51ae80-9e71-11e9-9748-a4b5c2c24ffc.png)
![image](https://user-images.githubusercontent.com/37869674/60658609-2e7dcc00-9e71-11e9-81ed-ab5b57ae2cd1.png)
![image](https://user-images.githubusercontent.com/37869674/60658625-36d60700-9e71-11e9-8583-df68f99504ec.png)
![image](https://user-images.githubusercontent.com/37869674/60658636-3b9abb00-9e71-11e9-858d-df2611e5dcf7.png)
![image](https://user-images.githubusercontent.com/37869674/60658640-3f2e4200-9e71-11e9-8f0a-a46f100e43e9.png)

![image](https://user-images.githubusercontent.com/37869674/60658653-42c1c900-9e71-11e9-8ce1-14203af941de.png)

**Comment by parthiban25** [comment]
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by parthiban25** [comment]
hi Badam,

kindly update the latest Deliverables in proforma invoice
1.New Development
2.correction

**Comment by badamnarendra028** [comment]
[nsoinpr_inv_p1_grd1_gr3.zip](https://github.com/astpl1998/Subhasri/files/3381574/nsoinpr_inv_p1_grd1_gr3.zip)

**Comment by parthiban25** [comment]
hi
sp is ok .
kindly update the Latest Design

**Comment by raju-kurup** [comment]
Latest sp and updated submitted to Ramco
